ALTER TABLE businesses
    ADD COLUMN IF NOT EXISTS facebook VARCHAR(255),
    ADD COLUMN IF NOT EXISTS instagram VARCHAR(255),
    ADD COLUMN IF NOT EXISTS x_twitter VARCHAR(255),
    ADD COLUMN IF NOT EXISTS tiktok VARCHAR(255);
